apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-monitor
  labels:
    app: metrics-monitor

spec:
  endpoints:
    - port: metrics
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: app-postgres
