auth:
  enablePostgresUser: true
  postgresPassword: "password"
  username: "user"
  password: "password"
  database: "users"

primary:
  persistence:
    enabled: false
    existingClaim: "postgres-pv-claim"
