auth:
  enablePostgresUser: true
  postgresPassword: "password"
  username: "postgres"
  password: "password"
  database: "postgres"

primary:
  persistence:
    enabled: true
    existingClaim: "postgres-pv-claim"
