{
 "title": "gin-users",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate 500",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (rate(promhttp_metric_handler_requests_total{code=\"500\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method) (rate(request_seconds_bucket{addr!=\"/metrics\", status=\"200\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(request_seconds_count{}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, method) (rate(request_seconds_bucket{addr!=\"/metrics\", status=\"200\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (response time) max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, method) (rate(request_seconds_bucket{addr!=\"/metrics\", status=\"200\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(request_seconds_bucket{addr!=\"/metrics\", status=\"200\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}