apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-postgres
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: app-postgres
                  port:
                    number: 8000
