apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-postgres
  labels:
    app: app-postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-postgres
  template:
    metadata:
      labels:
        app: app-postgres
    spec:
      containers:
      - name: app-postgres
        image: rosignol/gin_users_hw:1.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 8000
        # livenessProbe:
        #   httpGet:
        #     path: /api/healthchecker
        #     port: 8000
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        envFrom:
          - secretRef:
              name: postgres-secret
          - configMapRef:
              name: service-config
