apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: default
data:
  POSTGRES_DRIVER: 'postgres'
  MIGRATIONS_SOURCE: 'file://db/migrations'
  POSTGRES_HOST: 'postgres-postgresql'
  POSTGRES_PORT: '5432'
  POSTGRES_DB: 'users'
  PORT: '8000'
