apiVersion: batch/v1
kind: Job
metadata:
  name: "migration-job"
  labels:
    app: hw-postgres
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "migration-job-pod"
    spec:
      restartPolicy: Never
      containers:
        - name: app-postgres-migration
          image: rosignol/gin_users_hw:1.0.8
          imagePullPolicy: IfNotPresent
          command: ["/migration"]
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: service-config
      restartPolicy: Never
