apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: postgres
  DB_HOST: postgres-postgresql
  DB_DRIVER: postgres
  DB_USER: postgres
  DB_PASSWORD: password
  DB_NAME: postgres
  DB_PORT: 5432 
