apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: users
  DB_HOST: postgres-postgresql
  DB_DRIVER: postgres
  DB_USER: user
  DB_PASSWORD: password
  DB_NAME: users
  DB_PORT: 5432 
